[package]
name = "multicloud"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
argon2.workspace = true
axum.workspace = true
base64.workspace = true
clap.workspace = true
dialoguer.workspace = true
multicloud-authorization = { path = "../../crates/authorization" }
multicloud-admin = { path = "../admin" }
multicloud-agent = { path = "../agent" }
multicloud-api = { path = "../api" }
multicloud-configuration = { path = "../../crates/configuration" }
multicloud-identity = { path = "../../crates/identity" }
multicloud-messaging = { path = "../../crates/messaging" }
multicloud-migrations = { path = "../../migrations" }
multicloud-observability = { path = "../../crates/observability" }
multicloud-operation = { path = "../../crates/operation" }
multicloud-organization = { path = "../../crates/organization" }
multicloud-persistence = { path = "../../crates/persistence" }
multicloud-provider = { path = "../../crates/provider" }
multicloud-resource = { path = "../../crates/resource" }
multicloud-scheduler = { path = "../scheduler" }
multicloud-shared-kernel = { path = "../../crates/shared-kernel" }
multicloud-worker = { path = "../worker" }
rand.workspace = true
redis.workspace = true
sea-orm.workspace = true
sea-orm-migration.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[lints]
workspace = true
