[package]
name = "multicloud-agent"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
multicloud-observability = { path = "../../crates/observability" }
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
